// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mhippzfvluctflatbcbm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1oaXBwemZ2bHVjdGZsYXRiY2JtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNDkzNjIsImV4cCI6MjA2NTgyNTM2Mn0.V2dGwB-zyA16heZH-tQTmN9oja-h9Dv1mVtHILEvUa4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);